

name: integration

on:
 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:

jobs:
 
  build:
   
    runs-on: windows-latest
    
  
    steps:
     
      - uses: actions/checkout@v3

     
      - name: run ashok
        run: echo ashok

     
      - name: Run a multi-line 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
